name: Publish packages

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish package
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ secrets.ACTOR }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

